### ISSUE TITLE
add top level link to carbide docs

### ISSUE THREAD

**Issue by dweomer** [ranchergovernment/carbide#1]
**Describe the bug**
links to rancher docs but no link to carbide rancher docs

/cc @HoustonDad @jthapliya

**Comment by clanktron** [comment]
Are you talking about this? https://rancherfederal.github.io/carbide-docs/docs/registry-docs/configuration/rancher

Are you asking for two links or to replace the current rancher docs link with that?

**Comment by HoustonDad** [comment]
I believe we need to link to this, or somewhere near it: https://rancherfederal.github.io/carbide-docs/docs/intro

I think the Rancher link should be left as is. It points to the Rancher docs, where it should.

However Carbide is three pieces: the registry (which includes rancher images and the rest of the portfolio), stigatron and airgapped docs. Those should be linked either from the Carbide link above or grouped or something like that?
