### ISSUE TITLE
[BUG] [Dashboard] Feedback button should open in a new tab

### ISSUE THREAD

**Issue by Woovie** [ranchergovernment/carbide#3]
**Describe the bug**
When clicking "Feedback" in the top bar of the page, I am navigated in-tab. This should really open in a new tab.

**To Reproduce**
1. Login to the Carbide Dashboard
2. Click on Feedback
3. Your existing tab is navigated away from and you have to go back a page

**Expected behavior**
A new tab should be opened. The site is referencing an external webpage and as well, we should consider that if someone has feedback, it's likely about something they actively see in that moment. Navigating away then loses their context of the issue.

**Additional information**
I don't know specifics of new tab links, I do think it should also switch tabs and not simply open it in the background. This is behavior I'm basing off of past experience with other sites providing similar functionality.

**Comment by clanktron** [comment]
done
