### ISSUE TITLE
[BUG] Carbide Harvester cannot be used in an Airgapped Environment

### ISSUE THREAD

**Issue by HoustonDad** [ranchergovernment/carbide#9]
**Describe the bug**
Carbide Harvester can't be used in an Airgapped environment due to the helm charts attempting to use 'registry.rancher.com' vs docker.io, so they are pulled from the ISO itself.

**To Reproduce**
1. Download harvester-v1.3.1-carbide-1-amd64.iso via Hauler from AzureCR
2. Install harvester-v1.3.1-carbide-1-amd64.iso into an airgapped network (with NO external / internet connectivity)
3. Follow through install steps, after reboot, hit F-12, log in, watch k9s -> pods
4. All helm-operation pods fail due to ImagePullBackOff as the containers are attempting to pull from registry.rancher.com

**Expected behavior**
The helm operation pods should have used the rancher/shell that's located internally on the ISO

**Screenshots**
![image](https://github.com/user-attachments/assets/825d6c45-1543-44d7-9b88-931fa290e07e)
![image](https://github.com/user-attachments/assets/4690d4e9-e7ef-48a1-b6b6-495ce30705f5)

**Comment by zackbradys** [comment]
+1 to priority for this issue. I have a customer looking to test this on Wednesday (10/2).

**Comment by HoustonDad** [comment]
This has been fixed in harvester-v1.3.1-carbide-2-amd64.iso. Validated fixed
